-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoAm0DSe8zA6IP2Vt
LvYxg2Oenw4zk6TdgqZMytoDpkCgCgYIKoZIzj0DAQehRANCAATq6vltR1BxvKjK
u/stifmSq8Zv3O+nq7JTindKznsKwwC93wjvqnFS1+1Kv6dKFNQmnGjBQ/ARov3N
Svitij5I
-----END PRIVATE KEY-----